application: contact
version: 1
runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
  REDIS_CACHE_URL: redis://10.0.0.3:6379

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /data
  static_dir: data

- url: /widget
  static_dir: widget

- url: .*
  script: main.application
- url: /widget
  static_dir: widget

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "1.4"

